### ISSUE TITLE
Terraform is unable to start VM with Image ID 0

### ISSUE THREAD

**Issue by Th0masL** [OpenNebula/terraform-provider-opennebula#157]
**Description**

Terraform is unable to start a VM if the Image ID is the ID 0.

**To Reproduce**

The easiest way to reprocude is to install a fresh installation of OpenNebula, so there are no Images uploaded on the Datastore just yet. Then upload the very first Image (it should get ID 0) and then try to provision a VM with it with Terraform.

The VM will be broken.

**Expected behavior**

I'm expecting the VM to start normally.

**How to bypass the problem**

Upload the first Image (ID 0), then delete it, and re-upload it again so it gets the ID 1.

**Suggested fix**

Either fix the Image ID `0` bug on Terraform's side, or fix it on ONE's side, by defining that the lowest Image ID number should be `1` instead of `0`.

**Details**
 - Terraform Provider Version: 0.3.0
 - Hypervisor: KVM
 - ONE Version: 6.0.0.2

**Additional context**
_None_

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by jaypif** [comment]
Hi @Th0masL ,

Thanks for opening such issue. However we already faced this one and I thought we fixed it in 0.3.0.

We will take a look to check if there are remaining bugs. 

I agree with you that OpenNebula object should never start at 0 but 1. It is the same for all other objects.

Regards

**Comment by Th0masL** [comment]
Has this been fixed ? As far as I'm aware the problem is still present

**Comment by frousselet** [comment]
Sorry for the delay.
This bug will be fixed on the `0.5.2` version if we manage to reproduce it.

Did you get it on other version than `0.3.0`?

**Comment by Th0masL** [comment]
No worries, the workaround is pretty easy so it's not a big blocker.

Talking about trying to reproduce it with a version newer than `v0.3.0`: I tried to upgrade to `v0.5.0` but I had to rollback to `v0.3.0` due to this regression https://github.com/OpenNebula/terraform-provider-opennebula/issues/289, so I can't test just yet.

**Comment by treywelsh** [comment]
With the 0.3.0 release of the provider I have this error:
```Error: OpenNebula error [INTERNAL]: [one.vm.allocate] DISK 0: Unknown disk type```

I don't have any error with 0.4.3 and 0.5.1 releases.
#289 has been fixed and is part of 0.5.1 which has been released. Feel free to drop a comment If you reproduce the problem.

**Comment by treywelsh** [comment]
Hi @Th0masL 

Did you try to reproduce this problem from the 0.5.1 release of the provider ?

**Comment by Th0masL** [comment]
I can confirm that the problem is fixed with the more recent version of the provider, thanks !
I'm closing this issue.
