### ISSUE TITLE
OS section is deleted when updating CONTEXT

### ISSUE THREAD

**Issue by Th0masL** [OpenNebula/terraform-provider-opennebula#169]
Hi,

I'm actively continuing my tests with the almost latest version of the master branch 😃 

I'm currently using the branch `treywelsh:B-167`, which is the most up-to-date master branch that is working after the recent problems we had with building from master.

I found another possible problem : When running `terraform apply` to update the `CONTEXT` values of an existing VM, the `OS` values are deleted.

For example, after running `terraform apply`, when I go on the VM from the UI, and I click on `Update` > `Advanced` Tab, the following block is gone :
```
OS = [
  ARCH = "x86_64",
  BOOT = "disk0",
  UUID = "271d0115-27ea-4464-ba4f-023f1d9a3e43" ]
```

**Comment by treywelsh** [comment]
Related to #145 

Context update should be tested via virtual machine acceptance tests, I'll need to check why I didn't see this...

It seems that I didn't understood how the `one.vm.updateconf` XML-RPC method works, [described here](https://docs.opennebula.io/5.12/integration/system_interfaces/api.html#one-vm-updateconf).

I thought that I could pass only the updated sections when modified but this doesn't seems to work this way.
I did the operation via sunstone and registered a hook to see API events: it seems that the `updateconf` method receive the whole template content. Even some attributes that are not described in the documentation are passed like `CPU`, `MEMORY`... I suppose that they are ignored ?
The `updateconf` method seems to almost work like `update` method with `replace` behavior parameter.
I suppose that I should retrieve the whole VM template, make my modification on this template, then submit it via `updateconf` method.
Append new elements is easy, the case that seems a bit more tricky is when I'll need to remove a key: I'll need to retrieve the  config from terraform before and after user changes, then retrieve the keys removed by the user and then remove these elements from the template.
For other keys I'll just need to add/replace elements if they are new or not.

Could you confirm the behavior @christian7007 please ?

**Comment by treywelsh** [comment]
Here is a try to fix this behavior: #171 
To facilitate the test I pushed the same branch, but rebased on top of B-167 to avoid all other knowns problems:  [B-169-fix-vm-config-update-rebased](https://github.com/treywelsh/terraform-provider-opennebula/tree/B-169-fix-vm-config-update-rebased)

Feel free to give it a try

**Comment by Th0masL** [comment]
Hi ! Sorry for the late answer.

I've just rebuilt from the branch `B-169-fix-vm-config-update` and tried to update context.

Both `OS` and `GRAPHICS` are still getting deleted, so unless I did something wrong, the problem is still here

**Comment by treywelsh** [comment]
It's a bit confusing, but I made a second branch rebased on top of B-167 to allow you to test all at the same time:  [B-169-fix-vm-config-update-rebased](https://github.com/treywelsh/terraform-provider-opennebula/tree/B-169-fix-vm-config-update-rebased)

**Comment by Th0masL** [comment]
My bad, I misread, sorry ! I'll try this new branch

**Comment by Th0masL** [comment]
Well, so with the branch `B-169-fix-vm-config-update-rebased` the context update are not working anymore.
It's the same behavior as the current release 0.3.0, where it shows that the Context need to be updated, and it's saying that it got updated successfully, but nothing is in fact changed on the VM.

**Comment by treywelsh** [comment]
It works for my tests (add/remove/update context element). Do you have something to help me reproduce the problem ?
I'm using the provider built on top on B-169-fix-vm-config-update-rebased with terraform 0.15.5.
I use minione with Opennebula 5.12.0.4.

**Comment by Th0masL** [comment]
I'm using the latest version of OpenNebula (6.0.0.2) and the latest version of Terraform

I'll try to enable some more debug to give you more details, but not sure it will help

**Comment by Th0masL** [comment]
Ok so I've been doing some more testing.

I was able to run `terraform apply -destroy` and recreate everything with `terraform apply`, but then when I try to update the context values the command exit with an error.

Please find below the detailed logs :
## Preparing
```
# Go in the correct folder
> cd ~/github/treywelsh/terraform-provider-opennebula

# Pull the latest changes
> git pull
Already up to date.

# Show git branch
> git rev-parse --abbrev-ref HEAD
B-169-fix-vm-config-update-rebased

# Show git commit
> git rev-parse --short=7 HEAD
b1e74bc

# Create the folder where we will store the provider
> mkdir -p ~/.terraform.d/plugins/test/test-opennebula/opennebula/0.3.2/darwin_amd64

# Build the terraform provider as v0.3.2
> go build -o ~/.terraform.d/plugins/test/test-opennebula/opennebula/0.3.2/darwin_amd64/terraform-provider-opennebula

# Verify the success of the go build command
> echo $?
0

# Make the provider file executable
> chmod +x ~/.terraform.d/plugins/test/test-opennebula/opennebula/0.3.2/darwin_amd64/terraform-provider-opennebula

# Make sure there are no other providers
> find ~/.terraform.d/plugins/test/test-opennebula/opennebula -type f
/Users/thomas/.terraform.d/plugins/test/test-opennebula/opennebula/0.3.2/darwin_amd64/terraform-provider-opennebula

# Show terraform version
> terraform -v
Terraform v1.0.9
on darwin_amd64

# Enable Debug Mode
> export TF_LOG=DEBUG
```

Result of terraform plan/show :
```
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  ~ update in-place
Terraform will perform the following actions:
  # module.itm.module.haproxy1[0].opennebula_virtual_machine.haproxy[0] will be updated in-place
  ~ resource "opennebula_virtual_machine" "haproxy" {
      ~ context       = {
          ~ "TEST_VARIABLE"                  = "value123" -> "value1234"
        }
        id            = "293"
        name          = "haproxy1"
        tags          = {
            "environment" = "stage"
        }
    }
Plan: 0 to add, 1 to change, 0 to destroy.
```

Result of terraform apply :
```
2021-10-21T16:44:05.765+0300 [DEBUG] Starting graph walk: walkApply
2021-10-21T16:44:05.770+0300 [DEBUG] created provider logger: level=debug
2021-10-21T16:44:05.770+0300 [INFO]  provider: configuring client automatic mTLS
2021-10-21T16:44:05.780+0300 [DEBUG] provider: starting plugin: path=.terraform/providers/registry.terraform.io/hashicorp/random/3.1.0/darwin_amd64/terraform-provider-random_v3.1.0_x5 args=[.terraform/providers/registry.terraform.io/hashicorp/random/3.1.0/darwin_amd64/terraform-provider-random_v3.1.0_x5]
2021-10-21T16:44:05.786+0300 [DEBUG] provider: plugin started: path=.terraform/providers/registry.terraform.io/hashicorp/random/3.1.0/darwin_amd64/terraform-provider-random_v3.1.0_x5 pid=41604
2021-10-21T16:44:05.790+0300 [DEBUG] provider: waiting for RPC address: path=.terraform/providers/registry.terraform.io/hashicorp/random/3.1.0/darwin_amd64/terraform-provider-random_v3.1.0_x5
2021-10-21T16:44:05.813+0300 [INFO]  provider.terraform-provider-random_v3.1.0_x5: configuring server automatic mTLS: timestamp=2021-10-21T16:44:05.812+0300
2021-10-21T16:44:05.856+0300 [DEBUG] provider.terraform-provider-random_v3.1.0_x5: plugin address: address=/var/folders/nh/dvpnwyhs1y96jw4svdltk81c0000gn/T/plugin713219315 network=unix timestamp=2021-10-21T16:44:05.855+0300
2021-10-21T16:44:05.856+0300 [DEBUG] provider: using plugin: version=5
2021-10-21T16:44:05.889+0300 [DEBUG] created provider logger: level=debug
2021-10-21T16:44:05.889+0300 [INFO]  provider: configuring client automatic mTLS
2021-10-21T16:44:05.900+0300 [DEBUG] provider: starting plugin: path=.terraform/providers/test/test-opennebula/opennebula/0.3.2/darwin_amd64/terraform-provider-opennebula args=[.terraform/providers/test/test-opennebula/opennebula/0.3.2/darwin_amd64/terraform-provider-opennebula]
2021-10-21T16:44:05.905+0300 [DEBUG] provider: plugin started: path=.terraform/providers/test/test-opennebula/opennebula/0.3.2/darwin_amd64/terraform-provider-opennebula pid=41605
2021-10-21T16:44:05.907+0300 [DEBUG] provider: waiting for RPC address: path=.terraform/providers/test/test-opennebula/opennebula/0.3.2/darwin_amd64/terraform-provider-opennebula
2021-10-21T16:44:05.928+0300 [INFO]  provider.terraform-provider-opennebula: configuring server automatic mTLS: timestamp=2021-10-21T16:44:05.928+0300
2021-10-21T16:44:05.940+0300 [DEBUG] provider.terraform-provider-opennebula: plugin address: address=/var/folders/nh/dvpnwyhs1y96jw4svdltk81c0000gn/T/plugin270908726 network=unix timestamp=2021-10-21T16:44:05.939+0300
2021-10-21T16:44:05.940+0300 [DEBUG] provider: using plugin: version=5
2021-10-21T16:44:05.955+0300 [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unimplemented desc = unknown service plugin.GRPCStdio"
2021-10-21T16:44:05.957+0300 [DEBUG] No provider meta schema returned
2021-10-21T16:44:06.000+0300 [WARN]  Provider "test/test-opennebula/opennebula" produced an invalid plan for module.infra.module.haproxy1[0].opennebula_virtual_machine.haproxy[0], but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .pending: planned value cty.False for a non-computed attribute
      - .template_id: planned value cty.NumberIntVal(-1) for a non-computed attribute
      - .nic[0].virtio_queues: planned value cty.StringVal("") for a non-computed attribute
      - .nic[0].mac: planned value cty.StringVal("") for a non-computed attribute
      - .nic[0].model: planned value cty.StringVal("") for a non-computed attribute
      - .nic[0].physical_device: planned value cty.StringVal("") for a non-computed attribute
      - .nic[1].virtio_queues: planned value cty.StringVal("") for a non-computed attribute
      - .nic[1].mac: planned value cty.StringVal("") for a non-computed attribute
      - .nic[1].model: planned value cty.StringVal("") for a non-computed attribute
      - .nic[1].physical_device: planned value cty.StringVal("") for a non-computed attribute
module.infra.module.haproxy1[0].opennebula_virtual_machine.haproxy[0]: Modifying... [id=292]
2021-10-21T16:44:06.009+0300 [INFO]  Starting apply for module.infra.module.haproxy1[0].opennebula_virtual_machine.haproxy[0]
2021-10-21T16:44:06.010+0300 [DEBUG] module.infra.module.haproxy1[0].opennebula_virtual_machine.haproxy[0]: applying the planned Update change
2021-10-21T16:44:07.631+0300 [DEBUG] provider.terraform-provider-opennebula: 2021/10/21 16:44:07 [DEBUG] Update context
2021-10-21T16:44:07.631+0300 [DEBUG] provider.terraform-provider-opennebula: 2021/10/21 16:44:07 [DEBUG] Waiting for state to become: [RUNNING]
module.infra.module.haproxy1[0].opennebula_virtual_machine.haproxy[0]: Still modifying... [id=292, 10s elapsed]
2021-10-21T16:44:17.634+0300 [DEBUG] provider.terraform-provider-opennebula: 2021/10/21 16:44:17 Refreshing VM state...
2021-10-21T16:44:19.243+0300 [DEBUG] provider.terraform-provider-opennebula: 2021/10/21 16:44:19 VM (ID:292, name:haproxy1) is currently in state ACTIVE and in LCM state RUNNING
2021-10-21T16:44:19.244+0300 [DEBUG] provider.terraform-provider-opennebula: 2021/10/21 16:44:19 [INFO] Update VM configuration: AUTOMATIC_DS_REQUIREMENTS="("CLUSTERS/ID" @> 0)"
2021-10-21T16:44:23.036+0300 [DEBUG] [aws-sdk-go]
╷
│ Warning: Applied changes may be incomplete
│
│ The plan was created with the -target option in effect, so some changes requested in the configuration may have been ignored and the output values may not be fully updated. Run the following command to verify that no
│ other changes are pending:
│     terraform plan
│
│ Note that the -target option is not suitable for routine use, and is provided only for exceptional situations such as recovering from errors or mistakes, or when Terraform specifically suggests to use it as part of an
│ error message.
╵
╷
│ Error: vm updateconf: OpenNebula error [INTERNAL]: [one.vm.updateconf] Parse error: syntax error, unexpected VARIABLE, expecting EQUAL or EQUAL_EMPTY at line 1, columns 50:76
│
│   with module.infra.module.haproxy1[0].opennebula_virtual_machine.haproxy[0],
│   on modules/haproxy/main.tf line 25, in resource "opennebula_virtual_machine" "haproxy":
│   25: resource "opennebula_virtual_machine" "haproxy" {
│
╵
2021-10-21T16:44:23.040+0300 [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2021-10-21T16:44:23.044+0300 [DEBUG] provider: plugin process exited: path=.terraform/providers/registry.terraform.io/hashicorp/random/3.1.0/darwin_amd64/terraform-provider-random_v3.1.0_x5 pid=41604
2021-10-21T16:44:23.044+0300 [DEBUG] provider: plugin exited
2021-10-21T16:44:23.046+0300 [DEBUG] provider: plugin process exited: path=.terraform/providers/test/test-opennebula/opennebula/0.3.2/darwin_amd64/terraform-provider-opennebula pid=41605
2021-10-21T16:44:23.046+0300 [DEBUG] provider: plugin exited
```

**Comment by Th0masL** [comment]
I have opened another ticket following this syntax error (which is only happening with this new version of the provider) : https://github.com/OpenNebula/terraform-provider-opennebula/issues/172

**Comment by treywelsh** [comment]
Seems due to some quote problems in the template we try to send to OpenNebula: 
```
AUTOMATIC_DS_REQUIREMENTS="("CLUSTERS/ID" @> 0)"
```

**Comment by Th0masL** [comment]
The thing that is strange is that with the current template that I have, I can run `terraform apply --destroy` to destroy all the VMs, and then run `terraform apply` to recreate them all.

It only throw this error when I update the values of the Context in the template and I re-run `terraform apply`.

And as you can see, the value I update is pretty simple :
```
~ "TEST_VARIABLE"                  = "value123" -> "value1234"
```

**Comment by treywelsh** [comment]
It's due to how I managed things internally I retrieved the whole template, updated it, then submit it to updateconf method.
To fix this I'll try to filter only relevant sections (listed in doc) before the update to avoid noise due to other attributes.
I just added a commit on top of `B-169-fix-vm-config-update-rebased` branch to fix this, you can give it a try

**Comment by Th0masL** [comment]
Hi ! I've just tried and everything seems working fine now. Good job !
